# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/development/cicd/templates/
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  image: gitlab.desy.de:5555/millepede/millepede-ii/mp2dev_base 
  stage: build
  script:
    - mkdir build install
    - cd build  
    - cmake -DCMAKE_INSTALL_PREFIX=../install ../ 
    - make 
    - make install
    - echo "Compile complete."
  artifacts: 
    name: "pede_installation"
    paths:
      - install/

doc-job:       # This job runs in the build stage, which runs first.
  image: gitlab.desy.de:5555/millepede/millepede-ii/mp2dev_base 
  stage: build
  script:
    - doxygen pede.f90   
    - echo "Doc complete."
    - cp -r html public
  artifacts: 
    name: "Doc"
    paths:
      - latex/ 
      - public/
    expose_as: "Documentation"

pede-runs: 
  stage: test
  image: gitlab.desy.de:5555/millepede/millepede-ii/mp2dev_base 
  needs: 
    - build-job
  script: 
    - ls 
    - source install/mp2setup.sh
    - pede -t 

generate-ref: 
  stage: test
  image: ${CI_REGISTRY_IMAGE}/mp2runtime:main
  script: 
    - pede -tBRLF
  artifacts:
    name: "RefOut"
    paths:
      - mp2tst.bin
      - mp2str.txt
      - mp2con.txt 
      - millepede.* 
    expire_in: 1 hour

test-align: 
  stage: test
  needs: 
    - generate-ref
    - build-job
  image: gitlab.desy.de:5555/millepede/millepede-ii/mp2dev_base 
  script: 
    - mv millepede.log ref.log 
    - mv millepede.res ref.res 
    - mv millepede.mon ref.mon 
    - mv millepede.his ref.his 
    - pede mp2str.txt 
    - diff millepede.log ref.log
    

runtime-image:
  stage: deploy 
  when: on_success
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_DESTINATION: ${CI_REGISTRY_IMAGE}/mp2runtime:${CI_COMMIT_REF_NAME}
    GIT_SSL_NO_VERIFY: "true"
  script:
    - echo  "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$GITLAB_USER\",\"password\":\"$GITLAB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context CI/runtime_image/ --dockerfile Dockerfile --build-arg GITLAB_USER=${GITLAB_USER} --build-arg GITLAB_TOKEN=${GITLAB_TOKEN} --destination $IMAGE_DESTINATION
    # Print the full registry path of the pushed image
    - echo "Image pushed successfully to ${IMAGE_DESTINATION}"
  interruptible: true
  only:
    - main

dev-image:
  stage: deploy 
  when: manual 
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_DESTINATION: ${CI_REGISTRY_IMAGE}/mp2dev_base:latest
    GIT_SSL_NO_VERIFY: "true"
  script:
    - echo  "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$GITLAB_USER\",\"password\":\"$GITLAB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context CI/dev_image/ --dockerfile Dockerfile --build-arg GITLAB_USER=${GITLAB_USER} --build-arg GITLAB_TOKEN=${GITLAB_TOKEN} --destination $IMAGE_DESTINATION
    - echo "Image pushed successfully to ${IMAGE_DESTINATION}"
  interruptible: true



pages:
  stage: deploy
  needs: 
    - doc-job
  script:
    - ls -l public
  artifacts:
    paths:
      - public
  only:
    - main
