FROM almalinux:9.6
RUN dnf --enablerepo=crb install -y cmake gcc-c++ gcc lapack  openblas zlib-devel git openblas-openmp gfortran blas-devel openblas-devel lapack-devel doxygen texlive-latex texlive-dvips ghostscript diff
